name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: windows-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'
      - name: Restore Dependencies
        run: dotnet restore C:\Users\coelh\source\repos\Ecommerce.API\src\Ecommerce.API\Ecommerce.API.sln

      - name: Build Application
        run: dotnet build C:\Users\coelh\source\repos\Ecommerce.API\src\Ecommerce.API\Ecommerce.API.sln --configuration Release

      - name: Publish Application
        run: dotnet publish C:\Users\coelh\source\repos\Ecommerce.API\src\Ecommerce.API\Ecommerce.API.sln -c Release -o ./publish

      - name: Deploy to Dev
        if: contains(github.event.pull_request.head.ref, 'dev') && github.event.pull_request.merged
        run: |
          # Etapas para implantar no ambiente de desenvolvimento
          echo "Deploying to Dev environment..."

      - name: Deploy to HML
        if: contains(github.event.pull_request.head.ref, 'hml') && github.event.pull_request.merged
        run: |
          # Etapas para implantar no ambiente de homologação
          echo "Deploying to HML environment..."

      - name: Deploy to Prod
        if: contains(github.event.pull_request.head.ref, 'prod') && github.event.pull_request.merged
        run: |
          # Etapas para implantar no ambiente de produção
          echo "Deploying to Prod environment..."